// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbLu_mettQ_jjr76WJapr6t3uV7yOzxME',
    appId: '1:883945467467:web:72693d93472d7b1a70e7ce',
    messagingSenderId: '883945467467',
    projectId: 'mywardrobe-5b44f',
    authDomain: 'mywardrobe-5b44f.firebaseapp.com',
    storageBucket: 'mywardrobe-5b44f.firebasestorage.app',
    measurementId: 'G-KZE9J5FNFZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCYOpNChtgluCgq7AaO6Xg2MJmqYxW-B8',
    appId: '1:883945467467:android:48daf08b545285df70e7ce',
    messagingSenderId: '883945467467',
    projectId: 'mywardrobe-5b44f',
    storageBucket: 'mywardrobe-5b44f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwNkILlnZIsU0PQoDhiMeX2IMdPlSW8JI',
    appId: '1:883945467467:ios:a2c539f1c867f7f870e7ce',
    messagingSenderId: '883945467467',
    projectId: 'mywardrobe-5b44f',
    storageBucket: 'mywardrobe-5b44f.firebasestorage.app',
    iosBundleId: 'com.example.mywardrobe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwNkILlnZIsU0PQoDhiMeX2IMdPlSW8JI',
    appId: '1:883945467467:ios:a2c539f1c867f7f870e7ce',
    messagingSenderId: '883945467467',
    projectId: 'mywardrobe-5b44f',
    storageBucket: 'mywardrobe-5b44f.firebasestorage.app',
    iosBundleId: 'com.example.mywardrobe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbLu_mettQ_jjr76WJapr6t3uV7yOzxME',
    appId: '1:883945467467:web:d74390badad86d4770e7ce',
    messagingSenderId: '883945467467',
    projectId: 'mywardrobe-5b44f',
    authDomain: 'mywardrobe-5b44f.firebaseapp.com',
    storageBucket: 'mywardrobe-5b44f.firebasestorage.app',
    measurementId: 'G-E1W3ZWBNRF',
  );
}
